/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.text.SimpleDateFormat;

/**
 *
 * @author a c e r
 */

public class customerForm extends javax.swing.JFrame {
public String tanggal;
    
    private void tampilkan_data_transaksi(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No Transaksi");
        model.addColumn("Id Pemebeli");
        model.addColumn("Id Roti");
        model.addColumn("Tgl Transaksi");
        model.addColumn("Jumlah Beli");
        
        try{
            String sql = "SELECT * FROM transaksi";
            PreparedStatement ps=null;
            Object [] row={"Nomor Transaksi", "Id Pembeli", "Id Roti", "Tanggal Transaksi", "Jumlah Beli"};
            DefaultTableModel dtm=new DefaultTableModel(null,row);
                tabelTransaksi.setModel(dtm);
                jScrollPane3.setEnabled(true);
                jScrollPane3.setBorder(null);
                jScrollPane3.setViewportView(tabelTransaksi);
            java.sql.ResultSet rs=null;
            ps=Konfig.configDB().prepareStatement(sql);
            rs=ps.executeQuery();
                while (rs.next()){
                    String no_transaksi=rs.getString(1);
                    String id_pembeli=rs.getString(2);
                    String id_roti=rs.getString(3);
                    String tgl_transaksi=rs.getString(4);
                    String jumlah_beli=rs.getString(5);
                    
                    String [] baris={no_transaksi,id_pembeli,id_roti,tgl_transaksi,jumlah_beli};
                    dtm.addRow(baris);
                }
            
        }catch(SQLException e){}
    }
    private void tampilkan_data_produk(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("Nama");
        model.addColumn("Harga");
        model.addColumn("Stok");
        model.addColumn("Id pegawai");
        
        try{
            int no=1;
            String sql = "SELECT * FROM produk";
            java.sql.Connection conn = (Connection) Konfig.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            
            while(res.next()){
                model.addRow(new Object[] {res.getString(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5)});
            }
            tabelRoti.setModel(model);
        }catch (SQLException e){
            System.out.println("Error : " + e.getMessage()); 
        }
    }
    private void tampilkan_data_pembeli(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("Nama");
        model.addColumn("Kontak");
        model.addColumn("Alamat");
        
        try{
            String sql = "SELECT * FROM pembeli";
            java.sql.Connection conn = (Connection) Konfig.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            
            while(res.next()){
                model.addRow(new Object[] {res.getString(1),res.getString(2),res.getString(3),res.getString(4)});
            }
            tabelPem.setModel(model);
        }catch (SQLException e){
            System.out.println("Error : " + e.getMessage()); 
        }
    }
    public customerForm() {
        initComponents();
        tampilkan_data_produk();
        tampilkan_data_pembeli();
        tampilkan_data_transaksi();
                
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelRoti = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelPem = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        buyButton = new javax.swing.JButton();
        txtTotal = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtJumlah = new javax.swing.JTextField();
        txtstok = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        txtHarga = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtiroti = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtidpem = new javax.swing.JTextField();
        txtnamapem = new javax.swing.JTextField();
        txtkontakpem = new javax.swing.JTextField();
        txtAl = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        pembutton = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        panelTrans = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        dttgl = new com.toedter.calendar.JDateChooser();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelTransaksi = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 0, 0));

        tabelRoti.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelRoti.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelRotiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelRoti);

        tabelPem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelPem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelPemMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelPem);

        jPanel4.setBackground(new java.awt.Color(255, 234, 167));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buyButton.setText("Beli");
        buyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyButtonActionPerformed(evt);
            }
        });
        jPanel4.add(buyButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 270, 93, -1));

        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });
        jPanel4.add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 276, 240, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 2, 18)); // NOI18N
        jLabel3.setText("Total Harga");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 274, -1, -1));

        jLabel2.setText("Jumlah");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 228, -1, -1));

        txtJumlah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtJumlahKeyReleased(evt);
            }
        });
        jPanel4.add(txtJumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 224, 240, -1));
        jPanel4.add(txtstok, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 167, 240, -1));

        jLabel4.setText("Stok Barang");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 171, -1, -1));

        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });
        jPanel4.add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 60, 240, -1));
        jPanel4.add(txtHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 113, 240, -1));

        jLabel5.setText("Harga");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 117, -1, -1));

        jLabel6.setText("Nama Roti");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 60, -1, -1));

        jLabel9.setText("Id Roti");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 22, -1, -1));
        jPanel4.add(txtiroti, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 18, 240, -1));

        jPanel2.setBackground(new java.awt.Color(46, 204, 113));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(46, 204, 113));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(60, 63, 65));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("List Roti");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, -1, -1));

        jPanel5.setBackground(new java.awt.Color(204, 204, 0));

        jLabel10.setText("Id Pembeli");

        jLabel12.setText("Nama Pemebeli");

        jLabel13.setText("Kontak");

        jLabel14.setText("Alamat");

        txtnamapem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamapemActionPerformed(evt);
            }
        });

        txtkontakpem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkontakpemActionPerformed(evt);
            }
        });

        txtAl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(60, 63, 65));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Untuk memilih roti, bisa dengan mengklik id roti pada tabel. ");

        pembutton.setText("Simpan");
        pembutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pembuttonActionPerformed(evt);
            }
        });

        jLabel16.setText("Untuk pembeli yang belum pernah bertransaksi");

        jLabel17.setText("Silahkan isi data pembeli dibawah ini, kemudian klik tombol \"Save\"");

        jLabel18.setBackground(new java.awt.Color(46, 204, 113));
        jLabel18.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(60, 63, 65));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel18.setText("Data Pembeli");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGap(74, 74, 74)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel14)
                                .addComponent(jLabel13))
                            .addGap(61, 61, 61))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel12)
                            .addGap(39, 39, 39)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel10)
                        .addGap(53, 53, 53)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(txtAl, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 156, Short.MAX_VALUE)
                        .addComponent(pembutton)
                        .addGap(54, 54, 54))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtidpem, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtkontakpem, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(txtnamapem, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jLabel17))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(jLabel18))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(112, 112, 112))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addGap(46, 46, 46)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtidpem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnamapem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtkontakpem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pembutton)
                    .addComponent(txtAl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addGap(20, 20, 20))
        );

        panelTrans.setBackground(new java.awt.Color(255, 255, 51));

        jLabel11.setText("Tgl Transaksi");

        dttgl.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dttglPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout panelTransLayout = new javax.swing.GroupLayout(panelTrans);
        panelTrans.setLayout(panelTransLayout);
        panelTransLayout.setHorizontalGroup(
            panelTransLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel11)
                .addGap(39, 39, 39)
                .addComponent(dttgl, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(283, Short.MAX_VALUE))
        );
        panelTransLayout.setVerticalGroup(
            panelTransLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelTransLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(dttgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(212, 212, 212))
        );

        jPanel3.setBackground(new java.awt.Color(97, 204, 148));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(60, 63, 65));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Proses Transaksi");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 30, -1, -1));

        jPanel6.setBackground(new java.awt.Color(51, 255, 255));

        jLabel15.setBackground(new java.awt.Color(46, 204, 113));
        jLabel15.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(60, 63, 65));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("List Data Pembeli");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(202, 202, 202))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel15)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        tabelTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tabelTransaksi);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 692, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelTrans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 692, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 624, Short.MAX_VALUE))
                        .addContainerGap())))
            .addComponent(jScrollPane3)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelTrans, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    private void txtJumlahKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtJumlahKeyReleased
        // TODO add your handling code here:
        Integer stok,hrgjual,jmljual,jmlharga;
         stok=Integer.parseInt(txtstok.getText());
         hrgjual=Integer.parseInt(txtHarga.getText());
         jmljual=Integer.parseInt(txtJumlah.getText());
         
         if(stok < jmljual){
             JOptionPane.showMessageDialog(rootPane, "Stok roti kurang");
             txtJumlah.setText("");
             txtTotal.setText("");
         }else{
             jmlharga=(hrgjual*jmljual);
             txtTotal.setText(String.valueOf(jmlharga));
             
         }
    }//GEN-LAST:event_txtJumlahKeyReleased

    private void tabelRotiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelRotiMouseClicked
        // TODO add your handling code here:
        int baris = tabelRoti.rowAtPoint(evt.getPoint());
        String ID = tabelRoti.getValueAt(baris, 0).toString();
        txtiroti.setText(ID);
        String Nama = tabelRoti.getValueAt(baris, 1).toString();
        txtNama.setText(Nama);
        String Harga = tabelRoti.getValueAt(baris, 2).toString();
        txtHarga.setText(Harga);
        String Stok = tabelRoti.getValueAt(baris, 3).toString();
        txtstok.setText(Stok);
    }//GEN-LAST:event_tabelRotiMouseClicked

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    private void txtkontakpemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkontakpemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkontakpemActionPerformed

    private void tabelPemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelPemMouseClicked
        // TODO add your handling code here:
        int baris = tabelPem.rowAtPoint(evt.getPoint());
        String ID = tabelPem.getValueAt(baris, 0).toString();
        txtidpem.setText(ID);
        String Nama = tabelPem.getValueAt(baris, 1).toString();
        txtnamapem.setText(Nama);
        String kontak = tabelPem.getValueAt(baris, 2).toString();
        txtkontakpem.setText(kontak);
        String alamat = tabelPem.getValueAt(baris, 3).toString();
        txtAl.setText(alamat);
    }//GEN-LAST:event_tabelPemMouseClicked

    private void dttglPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dttglPropertyChange
        // TODO add your handling code here:
        try{
            if(dttgl.getDate()!=null){
                String ubah = "yyyy/MM/dd";
                SimpleDateFormat format= new SimpleDateFormat (ubah);
                tanggal=String.valueOf(format.format(dttgl.getDate()));
            }
        }catch (Exception e){
            
        }
    }//GEN-LAST:event_dttglPropertyChange

    private void buyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyButtonActionPerformed
            // TODO add your handling code here:
        try{
            if((txtidpem.getText().equals(""))
               ||(txtiroti.getText().equals(""))
               ||(txtJumlah.getText().equals("")))
               {
                 JOptionPane.showMessageDialog(rootPane, "Pengisian data salah");
               }else{
                 PreparedStatement ps = null;
                 String sql="Insert into transaksi (id_pembeli, id_roti, tgl_transaksi, Jumlah_beli) values"+
                         "('"+txtidpem.getText()+"','"+txtiroti.getText()+"','"+tanggal+"','"+txtJumlah.getText()+"')";
                 ps=Konfig.configDB().prepareStatement(sql);
                 ps.executeUpdate(sql);
                 JOptionPane.showMessageDialog(rootPane, "Data disimpan");
                 tampilkan_data_transaksi();
                 
                 Integer stok, jumlah, sisa;
                 stok=Integer.parseInt(txtstok.getText());
                 jumlah=Integer.parseInt(txtJumlah.getText());
                 sisa=stok-jumlah;
                 String sqlA = "update produk set stok='"+ sisa +"' where id_roti='"+txtiroti.getText()+"'";
                 
                 ps=Konfig.configDB().prepareStatement(sqlA);
                 ps.executeUpdate(sqlA);
                 tampilkan_data_transaksi();
                 tampilkan_data_produk();        
                 
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(rootPane, "Ada kesalahan di sistem");
        }  
        
    }//GEN-LAST:event_buyButtonActionPerformed

    private void pembuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pembuttonActionPerformed
        // TODO add your handling code here:
        try{
            if((txtidpem.getText().equals(""))
               ||(txtnamapem.getText().equals(""))
               ||(txtkontakpem.getText().equals(""))
               ||(txtAl.getText().equals("")))
               {
                 JOptionPane.showMessageDialog(rootPane, "Pengisian data salah");
               }else{
                 PreparedStatement ps = null;
                 String sql="Insert into pembeli (id_pembeli,nama_pembeli, Kontak_pembeli, Alamat) values"+
                         "('"+txtidpem.getText()+"','"+txtnamapem.getText()+"','"+txtkontakpem.getText()+"','"+txtAl.getText()+"')";
                 ps=Konfig.configDB().prepareStatement(sql);
                 ps.executeUpdate(sql);
                 JOptionPane.showMessageDialog(rootPane, "Data disimpan");
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(rootPane, "Ada kesalahan di sistem");
        }
        tampilkan_data_pembeli();
    }//GEN-LAST:event_pembuttonActionPerformed

    private void txtAlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlActionPerformed

    private void txtnamapemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamapemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamapemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(customerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(customerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(customerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(customerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new customerForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton buyButton;
    private com.toedter.calendar.JDateChooser dttgl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    public javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel panelTrans;
    public javax.swing.JButton pembutton;
    private javax.swing.JTable tabelPem;
    private javax.swing.JTable tabelRoti;
    private javax.swing.JTable tabelTransaksi;
    public javax.swing.JTextField txtAl;
    public javax.swing.JTextField txtHarga;
    public javax.swing.JTextField txtJumlah;
    public javax.swing.JTextField txtNama;
    public javax.swing.JTextField txtTotal;
    public javax.swing.JTextField txtidpem;
    private javax.swing.JTextField txtiroti;
    public javax.swing.JTextField txtkontakpem;
    private javax.swing.JTextField txtnamapem;
    private javax.swing.JTextField txtstok;
    // End of variables declaration//GEN-END:variables
}
